trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfig: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # hoặc version .NET bạn dùng

- script: dotnet restore backend/services/identity-service/IdentityService.API/IdentityService.API.csproj
  displayName: 'Restore IdentityService'

- script: dotnet build backend/services/identity-service/IdentityService.API/IdentityService.API.csproj --configuration $(buildConfig) --no-restore
  displayName: 'Build IdentityService'

- script: dotnet publish backend/services/identity-service/IdentityService.API/IdentityService.API.csproj --configuration $(buildConfig) --no-build --output $(Build.ArtifactStagingDirectory)/identity
  displayName: 'Publish IdentityService'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity'
    ArtifactName: 'identity-drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-fullstack-conn'
    appType: 'webApp'
    appName: 'fullstack-auth-api'
    package: '$(Build.ArtifactStagingDirectory)/identity/**/*.zip'
