trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfig: 'Release'

steps:
# Cài .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Khôi phục package
- task: DotNetCoreCLI@2
  displayName: 'Restore IdentityService'
  inputs:
    command: 'restore'
    projects: '**/IdentityService.API.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build IdentityService'
  inputs:
    command: 'build'
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig)'

# Publish
- task: DotNetCoreCLI@2
  displayName: 'Publish IdentityService'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/identity-service'
    zipAfterPublish: false

# 🔑 Lấy secret từ Key Vault
- task: AzureKeyVault@2
  displayName: 'Get secrets from Key Vault'
  inputs:
    azureSubscription: 'azure-fullstack-conn' # 👈 thay tên service connection thật
    KeyVaultName: 'truongfullstack-kv'
    SecretsFilter: 'AuthDBConnectionString'
    RunAsPreJob: true

- task: CmdLine@2
  displayName: 'List files in artifact staging directory'
  inputs:
    script: 'dir "$(Build.ArtifactStagingDirectory)\identity-service" /s'

# 🔁 Thay thế {{AuthDBConnectionString}} trong appsettings.json
- task: ReplaceTokens@5
  displayName: 'Replace {{Tokens}} in appsettings.json'
  inputs:
    targetFiles: '$(Build.ArtifactStagingDirectory)/identity-service/IdentityService.API/appsettings.json'
    encoding: 'auto'
    tokenPattern: 'custom'
    customTokenPattern: '\{\{(\w+)\}\}'

# Publish thư mục (not zip)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: identity-service'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-service'
    ArtifactName: 'identity-service'
    publishLocation: 'Container'
