trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfig: 'Release'

steps:
# Cài .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Khôi phục package
- task: DotNetCoreCLI@2
  displayName: 'Restore IdentityService'
  inputs:
    command: 'restore'
    projects: '**/IdentityService.API.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build IdentityService'
  inputs:
    command: 'build'
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig)'

# Publish
- task: DotNetCoreCLI@2
  displayName: 'Publish IdentityService'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/identity-service'
    zipAfterPublish: false

# 🔑 Lấy secret từ Key Vault
- task: AzureKeyVault@2
  displayName: 'Get secrets from Key Vault'
  inputs:
    azureSubscription: 'azure-fullstack-conn' # 👈 thay tên service connection thật
    KeyVaultName: 'truongfullstack-kv'
    SecretsFilter: 'AuthDBConnectionString'
    RunAsPreJob: true

# 🔁 Thay thế {{AuthDBConnectionString}} trong appsettings.json
- task: FileTransform@1
  displayName: 'Replace appsettings placeholders'
  inputs:
    folderPath: '$(Build.ArtifactStagingDirectory)/identity-service'
    fileType: 'json'
    targetFiles: '**/appsettings*.json'

# Publish thư mục (not zip)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: identity-service'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-service'
    ArtifactName: 'identity-service'
    publishLocation: 'Container'
