trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfig: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # hoặc version .NET bạn dùng

- task: DotNetCoreCLI@2
  displayName: 'Restore IdentityService'
  inputs:
    command: 'restore'
    projects: '**/IdentityService.API.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build IdentityService'
  inputs:
    command: 'build'
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig)'

- task: DotNetCoreCLI@2
  displayName: 'Publish IdentityService'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/identity-service'
    zipAfterPublish: false  # không tạo file .zip

# Publish thư mục (chứ không phải zip)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: identity-service'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-service'
    ArtifactName: 'identity-service'
    publishLocation: 'Container'
