trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfig: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # hoặc version .NET bạn dùng

- task: DotNetCoreCLI@2
  displayName: 'Restore IdentityService'
  inputs:
    command: 'restore'
    projects: '**/IdentityService.API.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build IdentityService'
  inputs:
    command: 'build'
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish IdentityService'
  inputs:
    command: 'publish'
    projects: '**/IdentityService.API.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/identity-service'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: identity-service'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-service'
    ArtifactName: 'identity-service'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-service'
    ArtifactName: 'identity-drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-fullstack-conn'
    appType: 'webApp'
    appName: 'fullstack-auth-api'
    package: '$(Build.ArtifactStagingDirectory)/identity/**/*.zip'
